now polls comments in separate table + optimized API calls
metron-labs/Azure-Sentinel pull request #8
Opened 2021-11-09 08:35 UTC by shikhin-metron

Furthermore, I have added some exception handlings so that it doesn't crash for simple things such as when there are no new incidents, alerts, or comments.

2021-11-10 08:48 UTC, kapil-metron requested changes

2021-11-10 08:48 UTC, kapil-metron commented on DataConnectors/Digital shadows/DigitalShadowsConnectorAzureFunction/DS_api.py
> +        items_url = self.url + "triage-items?id=" + str(item_id_str)
All the processing for creation of url should be inside this function

2021-11-10 08:48 UTC, kapil-metron commented on DataConnectors/Digital shadows/DigitalShadowsConnectorAzureFunction/DS_poller.py
>              event_dataJSON = self.DS_obj.get_triage_events(str(self.before_time), str(self.after_time))
Create subfunction for subtasks enclosed in the try-except block.

2021-11-11 08:04 UTC, shikhin-metron commented on DataConnectors/Digital shadows/DigitalShadowsConnectorAzureFunction/DS_api.py
> +        items_url = self.url + "triage-items?limit=1000&id=" + item_id_str
added limit because it was limiting to 10 items by default, hence giving incorrect results.

2021-11-11 08:10 UTC, kapil-metron approved these changes

2021-11-11 08:10 UTC, merged